plugins:
 - rubocop-minitest
 - rubocop-performance
 - rubocop-rake

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "test/fixtures/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockNesting:
  Max: 2

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash

Layout/LineLength:
  AllowURI: true
  Max: 160

Naming/FileName:
  Exclude:
    - "lib/simplecov-html.rb"
    - "test/test_simple_cov-html.rb"

Style/CollectionMethods:
  PreferredMethods:
    map: "collect"
    reduce: "inject"
    find: "detect"
    find_all: "select"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "comma"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "comma"
