name: mutant

on: [push, pull_request]

jobs:
  mutant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1.300.0
        with:
          ruby-version: ruby
          bundler-cache: true

      - run: bundle exec mutant run
